<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.epic</groupId>
    <artifactId>epic-api-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>shared</module>
        <module>api-gateway</module>
        <module>microservices/finance-service</module>
        <module>microservices/ai-service</module>
        <module>microservices/planner-service</module>
        <module>microservices/report-service</module>
        <module>microservices/auth-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <spring-boot.version>3.3.4</spring-boot.version>
        <spring-cloud-openfeign.version>4.1.3</spring-cloud-openfeign.version>
        <jjwt.version>0.11.5</jjwt.version>
        <springdoc.version>2.6.0</springdoc.version>
        <postgresql.version>42.7.3</postgresql.version>
        <lombok.version>1.18.26</lombok.version>
        <hibernate-types.version>2.21.1</hibernate-types.version>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <spring-messaging.version>6.2.5</spring-messaging.version>
        <spring-websocket.version>3.5.3</spring-websocket.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Cloud BOM -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-messaging</artifactId>
                <version>${spring-messaging.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-websocket</artifactId>
                <version>${spring-websocket.version}</version>
            </dependency>

            <!-- Common Dependencies -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>com.vladmihalcea</groupId>
                <artifactId>hibernate-types-60</artifactId>
                <version>${hibernate-types.version}</version>
            </dependency>

            <!-- Modules -->
            <dependency>
                <groupId>com.epic.shared</groupId>
                <artifactId>shared</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.api_gateway</groupId>
                <artifactId>api-gateway-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.auth</groupId>
                <artifactId>auth-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.finance</groupId>
                <artifactId>finance-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.ai</groupId>
                <artifactId>ai-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.planner</groupId>
                <artifactId>planner-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.epic.report</groupId>
                <artifactId>report-service</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
