server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ai-service
          uri: http://localhost:8081
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: finance-service
          uri: http://localhost:8083
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
        - id: planner-service
          uri: http://localhost:8084
          predicates:
            - Path=/planner/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://localhost:8085
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.epic.api_gateway: DEBUG

# Segurança
security:
  jwt:
    secret: your_jwt_secret_key
    expiration: 3600000 # 1 hora em ms
