spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://postgres:5432/epic_db}
    username: ${JDBC_DATABASE_USERNAME:epic}
    password: ${JDBC_DATABASE_PASSWORD:epic_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
